spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpadb
    username: sh
    password: sh
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: none # create, create-drop | update | none, validate
logging:
  level:
    root: info
    com.sh.app: debug